[tool.anchor]
version = "0.32.1"

[features]
seeds = true
skip-lint = false

[programs.devnet]
hot_perp = "9y5B6n8Lq8HipGsuwE7TrTW31y8T49xtFrZstYJeEV5w"

[programs.localnet]
hot_perp = "9y5B6n8Lq8HipGsuwE7TrTW31y8T49xtFrZstYJeEV5w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
genesis = [
]
